version: '{build}'

image: Visual Studio 2017

configuration: Release

init:
  - set PATH=C:\Qt\5.12.1\msvc2017_64\bin;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

install:
  - git submodule update --init --recursive

build_script:
  - mkdir build
  - cd build
  - cmake "-GNMake Makefiles" ..
  - nmake artefact

test: off

artifacts:
  - path: build/Robocut-*.zip
    name: Robocut
