os:
  - osx

language: cpp

dist: xenial
osx_image: xcode10.1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: "ppa:beineri/opt-qt-5.12.1-xenial"
      - sourceline: "ppa:snappy-dev/snapcraft-daily"
    packages:
      - gcc-7
      - g++-7
      - qt512-meta-minimal
      - qt512svg
      - qt512imageformats
      - qt512tools
      - snapcraft
      - libudev-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update ;
      brew install qt ;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CC=gcc-7 ;
      export CXX=g++-7 ;
      source /opt/qt512/bin/qt512-env.sh ;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export CMAKE_PREFIX_PATH=$(brew --prefix qt) ;
    fi
  - mkdir build
  - cd build
  - cmake ..
  - make artefact -j4
  - cd ..

before_deploy:
  - mkdir deploy
  - export VERSION=$(git describe --tags --always)
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cp build/Robocut-*.dmg deploy/Robocut-$VERSION.dmg ;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      snapcraft ;
      cp robocut_*.snap deploy/robocut_$VERSION.snap ;
    fi

deploy:
  skip_cleanup: true
  provider: gcs
  access_key_id: GOOGMAXVQITN5KRJFX4N
  secret_access_key:
    secure: NvHYmNPKHehn/WlBMtrFL6Bs2QZxTJoO5EDrVVkIj2Ycndregxx8kqCCW1qntY3O3XakSL7oSwdg7UoKz+PvjXStNX9cy+EGcvVqTurLSdD347SsO69NUv60NHsOaGMoEkkKYGP7kXBdSQgxuABP6072IrieiitEnU3kyui/SfMm77C3abEYfDQaOc7QRZEqkWvuAlhrI0qJ8E+65DbHxUCpUU+Yonf3sD75cZnAvdA67x/1b5O+8JULLwkVzAL86bc/ApaTe5h3d44Ti3S3dw5VlEbPfQ/DB+wv9X+lDIucjK4f47c3vhUs5aIK9e6XPYr7/V0lrTlKiSsTH9PagMqbqXSCMa+3QA7XITMfuF47NVquZCYV/M7jGyrrEKI5lE6R1OX74DU8XE05I94vDdOI67wlV4gd4luauVJIz7AS36eNYz1GqJOJsWwJ2nXLzsWqB/1MM2v986cFgVRpeqTP5h/ZBRPpXk/DapWqmwyZNm2uNqUsuVhMdIEsgYj2WdTeOvzZqIehwfg6yglcMxqMP3NogTtEjNMKkzZxhn0TBwxtY0HlyXXD3nYgf157PIVxEMYQLJAXdINN065PGJ9NXktZ/aeiy8a9xmHGOQW426g7dqPvLpDnDWCXVUglFUv2hAQFo6a+rWXcBE++ESpypTtfihXQHpHm+XZjmkI=
  bucket: osx_artefacts
  on:
    all_branches: true
    repo: Timmmm/robocut
  acl: public-read
  local_dir: deploy


