
trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- script: python3 -m pip install --upgrade pip setuptools wheel
  displayName: 'Upgrade Python nonsense'

- script: |
    brew install autoconf automake intltool gobject-introspection  libffi json-c libtool gettext
    which python3
    python3 --version
    pip3 --version
    pip3 install numpy
    pip3 show numpy
    pip3 show setuptools
    python3 -c 'import numpy'
    python3 -c 'import setuptools'
  displayName: 'Install requirements'
