
trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- script: python3 -m pip install --upgrade pip setuptools wheel
  displayName: 'Upgrade Python nonsense'

- script: |
    which python3
    python3 --version
    pip3 --version
    pip3 install -v numpy
    echo Showing numpy
    pip3 show -f numpy
    echo Numpy shown
    ls /usr/local/lib/python3.7/site-packages
    python3 -c 'import numpy'
  displayName: 'Install requirements'
