trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- script: python3 -m pip install --upgrade pip setuptools wheel
  displayName: 'Upgrade Python nonsense'

- script: |
    brew install autoconf automake intltool gobject-introspection libffi json-c libtool gettext
    which python3
    python3 --version
    pip3 --version
    pip3 install numpy
    pip3 show numpy
    pip3 show setuptools
    python3 -c 'import numpy'
    python3 -c 'import setuptools'
  displayName: 'Install requirements'

# - script: |
#     git clone https://github.com/mypaint/libmypaint
#     git clone https://github.com/mypaint/mypaint-brushes.git
#     mkdir install
#   displayName: 'Clone libmypaint and mypaint-brushes'

# - script: |
#     brew link --force gettext
#     cd libmypaint
#     ./autogen.sh
#     # i18n is disabled because it depends on some perl XML parser (yes
#     # really, in 2019) and I cannot get it to install properly.
#     ./configure --prefix=`pwd`/../install --disable-i18n
#     make -j4
#     make check
#     make install
#     brew unlink gettext
#   displayName: 'Build libmypaint'

# - script: |
#     cd mypaint-brushes
#     ./autogen.sh
#     ./configure --prefix=`pwd`/../install
#     make install
#   displayName: 'Build mypaint-brushes'

# - script: |
#     export PKG_CONFIG_PATH=../install/lib/pkgconfig/:../install/share/pkgconfig
#     export CFLAGS="-D_DARWIN_C_SOURCE"
#     python3 setup.py build
#   displayName: 'Build mypaint'
